export const INDUSTRIES = [
	{
		id: '1',
		name: 'Thực phẩm',
		icon: '/industries/food.svg',
		cover: '/industries/covers/food.png',
		application: {
			desc: 'HunterLab cung cấp các giải pháp đo màu cho protein thực vật, sữa thực vật, thịt thực vật và nhiều loại thực phẩm có nguồn gốc thực vật khác.',
			items: [
				'Thực phẩm ăn nhẹ',
				'Sản phẩm ngũ cốc',
				'Dầu ăn',
				'Chất béo rắn và đường bổ sung',
				'Thức ăn cho thú cưng',
				'Sản phẩm sữa',
				'Sản phẩm rau quả',
				'Thành phần thực phẩm',
				'Sản phẩm protein',
				'Và nhiều loại thực phẩm khác',
			],
		},
		products: ['1', '2', '5', '6', '7', '9', '10', '11', '12', '13'],
	},
	{
		id: '2',
		name: 'Đồ uống',
		icon: '/industries/drink.svg',
		cover: 'https://th.bing.com/th/id/R.5f92edff4fac370bdf83a7ad23b452aa?rik=xnGoyXezOo%2bqWw&riu=http%3a%2f%2feskipaper.com%2fimages%2fcoffee-beans-green-leaves-1.jpg&ehk=iyaIiWlN1%2bSV3DxAQMhX4DpQxKb3t13R57LTjV2Znrs%3d&risl=&pid=ImgRaw&r=0',
		application: {
			desc: 'Tại HunterLab, chúng tôi có các thiết bị đo màu đồ uống tiên tiến cho bất kỳ loại màu đồ uống nào.',
			items: [
				'Hạt cà phê rang',
				'Cà phê xay nhuyễn',
				'Nước ngọt',
				'Nước trái cây',
				'Nước lọc',
				'Thức uống bổ sung',
				'Và nhiều loại đồ uống khác',
			],
		},
		products: ['3', '4', '5', '6', '7', '12', '13'],
	},
	{
		id: '3',
		name: 'Nhựa',
		icon: '/industries/plastic.svg',
		cover: '/industries/covers/plastic.png',
		application: {
			desc: 'Với các công cụ chuyên dụng để đo màu nhựa của HunterLab, bạn có thể đánh giá nhiều loại sản phẩm khác nhau.',
			items: [
				'Chai nhựa',
				'Nhựa đúc',
				'Hạt nhựa',
				'Tròng kính mắt',
				'Và nhiều loại nhựa khác',
			],
		},
		products: ['1', '2', '7', '8', '9', '10', '11', '12', '13'],
	},
	{
		id: '4',
		name: 'Hóa học',
		icon: '/industries/chemistry.svg',
		cover: 'https://www.pixelstalk.net/wp-content/uploads/2016/12/Chemistry-Background-HD.jpg',
		application: {
			desc: 'Thiết bị HunterLab cung cấp các phép đo màu cực kỳ chính xác cho hóa chất, chất bôi trơn động cơ và dầu động cơ.',
			items: [
				'Hóa chất dạng bột (phân bón, bột than,...)',
				'Dầu động cơ',
				'Chất bôi trơn động cơ',
				'Xăng',
				'Và nhiều loại hóa phẩm khác',
			],
		},
		products: ['1', '2', '6', '7', '12'],
	},
	{
		id: '5',
		name: 'Dược phẩm',
		icon: '/industries/medic.svg',
		cover: 'https://image.freepik.com/free-photo/medicine-capsules-global-health-with-geometric-pattern-digital-remix_53876-126742.jpg',
		application: {
			desc: 'Tất cả các phòng thí nghiệm dược phẩm sinh học đều yêu cầu quét màu chính xác và các giải pháp đo màu dược phẩm sinh học của HunterLab tạo ra các phép đo chính xác một cách nhanh chóng.',
			items: [
				'Dược phẩm dạng bột',
				'Dược phẩm dạng viên nén/con nhộng',
				'Dược phẩm dạng lỏng',
				'Và nhiều loại dược phẩm khác',
			],
		},
		products: ['6', '12', '13'],
	},
	{
		id: '6',
		name: 'Xây dựng',
		icon: '/industries/building.svg',
		cover: 'https://live.staticflickr.com/3132/3174431207_44705860a6_b.jpg',
		application: {
			desc: 'Tại HunterLab, HunterLab thiết kế các công cụ đo màu cho vật liệu xây dựng với các chi tiết cụ thể như kết cấu và kích thước để có độ chính xác và tính nhất quán cao.',
			items: [
				'Xi măng',
				'Gạch',
				'Kính',
				'Vật liệu cách nhiệt',
				'Đá hoa cương',
				'Và nhiều loại vật liệu xây dựng khác',
			],
		},
		products: ['1', '2', '6', '8', '9', '10', '11', '12'],
	},
	{
		id: '7',
		name: 'Sơn và lớp phủ',
		icon: '/industries/arts.svg',
		cover: 'https://yarbroughindustries.com/wp-content/uploads/2020/11/AdobeStock_283496421-scaled.jpeg',
		application: {
			desc: 'HunterLab cung cấp một số dụng cụ đo lường phù hợp nhất cho sơn và lớp phủ công nghiệp, kiến ​​trúc và sơn cuộn.',
			items: [
				'Lớp phủ công nghiệp',
				'Lớp phủ công trình',
				'Lớp phủ cuộn',
				'Và nhiều loại lớp phủ khác',
			],
		},
		products: ['1', '9', '10', '11', '12'],
	},
	{
		id: '8',
		name: 'Giấy',
		icon: '/industries/printing.svg',
		cover: 'https://wallpaperaccess.com/full/5671129.jpg',
		application: {
			desc: 'HunterLab cung cấp các công cụ tiên tiến để đo màu giấy, cung cấp thông tin đáng tin cậy mà công ty bạn cần cho sản xuất và kiểm soát chất lượng.',
			items: [
				'Giấy bìa',
				'Hộp giấy',
				'Giấy in',
				'Giấy dán tường',
				'Và nhiều loại giấy khác',
			],
		},
		products: ['1', '9', '10', '11', '12', '13'],
	},
	{
		id: '9',
		name: 'Dệt may',
		icon: '/industries/sew.svg',
		cover: 'https://zeroequalstwo.net/wp-content/uploads/2020/12/red-thread.jpg',
		application: {
			desc: 'HunterLab có nhiều công cụ đo màu tiên tiến giúp doanh nghiệp của bạn cải thiện chất lượng và tốc độ quy trình sản xuất.',
			items: [
				'Denim',
				'Camouflage',
				'Và nhiều loại chất liệu khác',
			],
		},
		products: ['1', '8', '9', '10', '11', '12'],
	},
]
