export const PRODUCTS = [
    {
        id: "1",
        name: "Máy Đo Màu Quang Phổ Hunterlab Agera",
        image: "/products/agera_spectrophotometer-hunterlab.png",
        category: "1",
        industries: ["3", "4", "7", "8", "9"],
    },
    {
        id: "2",
        name: "Máy Đo Màu Quang Phổ ColorFlex EZ",
        image: "/products/colorflex-ez-spectrophotometer.png",
        category: "1",
        industries: ["1", "3", "4", "6"],
    },
    {
        id: "3",
        name: "Máy Đo Màu Cho Cà Phê ColorFlex EZ Coffee",
        image: "/products/ColorFlex_EZ_Coffee_2.png",
        category: "1",
        industries: ["2"],
    },
    {
        id: "4",
        name: "Máy Đo Màu Quang Phổ ColorFlex ColorFlex EZ Citrus",
        image: "/products/ColorFlex_EZ_Citrus.png",
        category: "1",
        industries: [2],
    },
    {
        id: "5",
        name: "Máy Đo Màu Quang Phổ ColorFlex EZ Tomato",
        image: "/products/ColorFlex_EZ_Tomato_3390_2_sauce.png",
        category: "1",
        industries: [1, 2],
    },
    {
        id: "6",
        name: "Máy Đo Màu Quang Phổ Hunterlab Aeros",
        image: "/products/aeros-spectrophotometer.png",
        category: "1",
        industries: [1, 2, 4, 5, 6],
    },
    {
        id: "7",
        name: "Máy Đo Màu Quang Phổ Hunterlab Vista",
        image: "/products/vista-spectrophotometer.png",
        category: "1",
        industries: [1, 2, 4],
    },
    {
        id: "8",
        name: "Máy Đo Màu Quang Phổ UltraScan PRO",
        image: "/products/ultrascan-pro-spectrophotometer.png",
        category: "1",
        industries: [3, 6, 9],
    },
    {
        id: "9",
        name: "Máy Đo Màu Di Động MiniScan EZ 4500",
        image: "/products/miniscan-ez-spectrophotometer.png",
        category: "2",
        industries: [1, 3, 6, 7, 9],
    },
    {
        id: "8",
        name: "Máy Đo Màu Di Động MiniScan EZ 4000",
        image: "/products/miniscan-ez-spectrophotometer.png",
        category: "2",
        industries: [6],
    },
    {
        id: "9",
        name: "Thiết Bị Phân Tích Màu Sắc Và Kiểm Soát Quy Trình SpectraTrend HT",
        image: "/products/spectratrend-ht-spectrophotometer.png",
        category: "3",
        industries: [1, 3, 7, 8, 9],
    },
    {
        id: "10",
        name: "EasyMatch QC: Phần Mềm Kiểm Soát Chất Lượng Màu",
        image: "/products/easymatch-qc-product.png",
        category: "3",
        industries: [],
    },
]