export const PRODUCTS = [
	{
		id: '1',
		name: 'Máy Đo Màu Quang Phổ Hunterlab Agera',
		image: '/products/agera_spectrophotometer-hunterlab.png',
		category: '1',
		industries: ['1', '3', '4', '6', '7', '8', '9'],
		desc: 'Từ nhà sản xuất hàng đầu thế giới về công nghệ đo màu, Agera của Hunterlab mang đến hình ảnh đầy đủ về chất lượng ngoại hình mẫu của bạn. Agera mang đến các phép đo đồng thời về màu sắc phản chiếu, độ bóng trong một phép đo đơn giản. Đèn LED cung cấp độ chính xác màu sắc và độ lặp lại vượt trội. Máy đo độ bóng tích hợp cho kết quả chính xác cao phù hợp với tiêu chuẩn quốc tế. Camera 5 megapixel đảm bảo định vị mẫu thích hợp trong khi chụp và lưu trữ hình ảnh như một phần của bản ghi dữ liệu. Máy đo màu quang phổ Agera với giao diện người dùng hiện đại, phần mềm kiểm soát chất lượng mạnh mẽ và các tùy chọn quản lý dữ liệu hiện đại mang đến tính linh hoạt đặc biệt và dễ sử dụng.',
		features: [
			'Đo màu và độ bóng đồng thời',
			'Hình học circumferential 0º/45ºc mô phỏng tầm nhìn của con người',
			'Nhiều khay để phù hợp với nhiều kích thước mẫu',
			'Kết nối USB và Ethernet',
			'Màn hình cảm ứng với giao diện người dùng hiện đại',
			'Phần mềm EasyMatch Essentials QC tích hợp',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [
					'Nguyên lý đo: Máy đo phổ phản xạ hai chùm tia / Máy đo độ bóng.',
					'Hình học: 0°/45° (chiếu sáng vòng tròn) ASTM E1164.',
					'Phương pháp đo: Cổng mở lên hoặc Cổng hướng về phía trước.',
					'Thời gian đọc: < 3 giây.',
					'Hình học độ bóng: 60 độ (60°).',
					'Chụp hình: Hình ảnh có độ phân giải cao, D65 chiếu sáng, chế độ xem hình 0°/45°, chụp hình và ghi nhớ hình ảnh.',
					'Mở cổng và khu vực đo:',
					'Lưu ý: Các lỗ mở tấm cổng của Agera được phóng to khoảng 3.174mm (1/8") để đảm bảo các vùng được chiếu sáng và được nhìn thấy của mẫu không bị cản trở bởi các cạnh của cổng. Vùng đo của Agera được điều khiển bởi các thấu kính trong hệ thống chứ không phải bởi kích thước lỗ mở cổng. Đây là một ưu điểm so với các thiết bị khác vì tấm cổng không ảnh hưởng đến phép đo.',
					'Kích thước lỗ mở:',
					'- Rất lớn: 53.97 mm (2.125 in).',
					'- Lớn: 28.57 mm (1.125 in).',
					'- Trung bình: 17.47 mm (0.688 in).',
					'Khu vực đo:',
					'- Màu sắc: Rất lớn - 50.8 mm (2 in), Lớn - 25.4 mm (1 in), Trung bình - 15.89 mm (5/8 in).',
					'- Độ bóng: 8 mm (5/16 in).',
				],
			},
			{
				title: 'Thông số kỹ thuật',
				desc: [
					'Phạm vi chiếu sáng: 360 nm - 700 nm.',
					'Phạm vi quang phổ: 400 nm - 700 nm.',
					'Thành phần phản xạ: Bị loại trừ.',
					'Độ phân giải phổ: < 3 nm.',
					'Băng thông hiệu dụng: 10 nm tam giác tương đương.',
					'Khoảng thời gian báo cáo: 10 nm.',
					'Phạm vi đo quang: 0 đến 150 %.',
					'Kiểm soát UV: Bao gồm UV và loại trừ UV với chế độ xem và báo cáo dữ liệu so sánh tự động. Hiệu chuẩn tại nhà máy với tùy chọn người dùng để hiệu chuẩn với tiêu chuẩn huỳnh quang cụ thể của họ.',
					'Nguồn sáng: Dãy đèn LED cân bằng toàn phổ.',
					'Tuổi thọ đèn LED: 5 năm (thông thường).',
					'Máy đo quang phổ: Quang học kín; dãy diode 256 phần tử; lưới ánh sáng hội tụ lõm độ phân giải cao.',
				],
			},
			{
				title: 'Hiệu suất',
				desc: [
					'Sự đồng nhất giữa các thiết bị đo màu (IIA):',
					'- Màu: ΔE 2000 < 0.15 CIE L*a*b* (Trung bình) trên bộ gạch CCSII (CERAM).',
					'- Độ bóng: 0-100 < 0.50 GU.',
					'Khả năng tái tạo:',
					'- Màu: ΔE 2000 < 0.03 CIE L*a*b* (Tối đa) trên gạch trắng.',
					'- Độ bóng: 0-100 < 0.1 GU.',
				],
			},
			{
				title: 'Giao diện người dùng',
				desc: [
					'Chế độ xem dữ liệu: EZ View, Bảng dữ liệu màu, Bảng dữ liệu phổ, Biểu đồ xu hướng.',
					'Các tính năng khác: Chỉ báo Pass/Fail (Đạt/KHÔNG Đạt), ghi nhãn và dấu thời gian, tự động đặt tên, tự động lưu, sao lưu và khôi phục dữ liệu.',
					'Các chỉ số và thông số đo: Chỉ số trắng E313, Độ nhạt màu, Chỉ số vàng E313, Chỉ số vàng D1925, Độ sáng Y, Tỷ lệ Z%, Độ sáng ở 457 nm, Đơn vị tương phản, HCCI, SCAA, ASTM E1349, Độ bóng: ASTM D523, ASTM D2457, ISO 2813, ISO 7668, JIS Z 8741.',
					'Thang màu: CIE L*a*b*, Hunter Lab, CIE LCh, CIE XYZ.',
					'Chỉ số khác biệt màu: ΔL*, ΔE*, ΔC*, ΔH*, ΔXYY, AXYZ.',
					'Các chỉ số khác biệt màu: ΔE*, ΔE*CMC, ΔE 2000.',
					'Lưu trữ dữ liệu: 8 GB (> 1 triệu bản ghi dữ liệu với hình ảnh).',
					'Các nguồn sáng: A, C, D50, D65, D75, F02, F07, F11.',
					'Quan sát viên: 2° và 10°.',
					'Ngôn ngữ: Tiếng Anh, Tiếng Nhật.',
					'Hiển thị: Màn hình cảm ứng, độ phân giải cao 1280x800.',
					'Phần mềm PC ngoài: Tương thích với HunterLab EasyMatch QC và Phần mềm Kiểm soát Chất lượng Dữ liệu Điện tử EasyMatch QC.',
				],
			},
			{
				title: 'Kết Nối I/O',
				desc: [
					'USB OTG: Kết nối với máy in, bàn phím, chuột.',
					'Cổng USB phía trước: Chuẩn 2.0 hai chiều, xuất/nhập dữ liệu qua ổ đĩa USB.',
					'Ethernet RJ45: In trực tiếp đến các máy in độc lập hoặc trên mạng, Gửi email trực tiếp từ thiết bị, Truyền dữ liệu đến hệ thống LIMS và SPC.',
					'Đầu vào ngoài: Công tắc chân từ xa hoặc thiết bị chuyển đổi tiếp xúc kín tương tự.',
					'Hỗ trợ truy cập từ xa: Kích hoạt thông qua công cụ hỗ trợ dựa trên internet.',
				],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [
					'Kích thước cảm biến:',
					'- Chiều cao: 28 cm (11 in)',
					'- Chiều rộng: 22 cm (8.75 in)',
					'- Chiều sâu: 31 cm (12.25 in)',
					'- Trọng lượng: 6.35 kg (14 lb)',
					'- Màn hình: Màn hình cảm ứng điện dung, độ phân giải cao, màu sắc, kích thước 17.8 cm (7 in), 1280 x 800',
					'Nguồn điện: Đầu vào từ 100 đến 240 VAC, 47 đến 63 Hz cho nguồn cấp điện phổ thông @ 24 VDC (3.75A 90W)',
					'Môi trường hoạt động: Nhiệt độ 4° đến 38° C (40° đến 100° F), Độ ẩm 10 % đến 85 % RH, không ngưng tụ',
					'Môi trường lưu trữ: Nhiệt độ -20° đến 65° C (-5° đến 150° F), độ ẩm 10 % đến 90 % RH, không ngưng tụ',
					'Các thành phần hệ thống:',
					'- Cảm biến Agera',
					'- Các tấm cổng: XLAV - 51 mm (2 in), LAV - 25.4 mm (1 in), MAV 16.9 mm (5/8 in)',
					'- Gạch trắng đã được hiệu chuẩn (Chứng chỉ NIST về truy xuất nguồn gốc)',
					'- Tiêu chuẩn kính đen đã được hiệu chuẩn dùng cho cả tiêu chuẩn hóa màu và độ bóng (Chứng chỉ truy xuất nguồn gốc ASTM D523, ISO 2813)',
					'- Gạch chẩn đoán màu xanh lá cây',
					'- Nguồn cấp điện phổ thông 100V - 240V',
					'- Hướng dẫn khởi động nhanh Agera',
					'- Hướng dẫn sử dụng Agera trên đĩa CD',
				],
			},
		],
		documents: [
			{
				title: 'Agera Brochure',
				href: 'https://www.hunterlab.com/media/documents/Agera_Brochure_02-23.pdf',
			},
			{
				title: 'Agera Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/agera-quick-start-guide.pdf',
			},
			{
				title: 'Agera Specifications',
				href: 'https://www.hunterlab.com/media/documents/Agera_Specifications_02-23.pdf',
			},
			{
				title: 'Agera User Manual',
				href: 'https://www.hunterlab.com/media/documents/Agera_Users_Manual_2.3_A60-1018-812.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/agera-port-configuration.png',
			'https://www.hunterlab.com/media/original_images/agera-sample-color-imaging.png',
			'https://www.hunterlab.com/media/original_images/agera-connection-ports.png',
		],
	},
	{
		id: '2',
		name: 'Máy Đo Màu Quang Phổ ColorFlex EZ',
		image: '/products/colorflex-ez-spectrophotometer.png',
		category: '1',
		industries: ['1', '3', '4', '6'],
		desc: 'Máy đo màu quang phổ thế hệ tiếp theo của Hunterlab- ColorFlex EZ giúp việc kiểm soát chất lượng màu đạt được độ hiệu quả cao nhất với thiết kế 45 ° / 0 ° cho độ chính xác tốt nhất trong việc so màu. Kết hợp tính linh hoạt, đơn giản và hiệu quả, ColorFlex EZ phản ánh gần 60 năm đổi mới của lĩnh vực đo màu trong một thiết bị nhỏ gọn, dễ sử dụng.',
		features: [
			'Máy so màu phản xạ của chất rắn và chất lỏng',
			'Lưu trữ theo tiêu chuẩn sản phẩm với dung sai Pass / Fail',
			'Thiết bị để bàn nhỏ gọn',
			'Có thể được kết nối với máy in hoặc PC',
			'Tương thích với phần mềm EasyMatch',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [
					'Nguyên lý đo: Máy quang phổ/máy đo màu để bàn hai chùm tia với thiết kế có thể sử dụng theo hai cách: hướng cổng lên trên hoặc hướng cổng về phía trước.',
					'Hình học đo: Chiếu sáng theo vòng tròn định hướng 45° / quan sát ở góc 0°.',
					'Máy quang phổ/máy đo màu: Hệ thống quang học kín; dãy diode 256 phần tử và lưới nhiễu xạ holographic lõm có độ phân giải cao.',
					'Đường kính cổng/Đường kính quan sát: 31,8 mm (1,25 inch) được chiếu sáng / 25,4 mm (1 inch) được đo.',
					'Thành phần phản xạ: Loại trừ.',
					'Dải quang phổ: 400 nm - 700 nm.',
					'Độ phân giải quang phổ: < 3 nm.',
					'Độ rộng dải hiệu dụng: 10 nm tương đương hình tam giác.',
					'Khoảng cách báo cáo: 10 nm.',
					'Phạm vi quang học: 0 đến 150%.',
					'Nguồn sáng: Đèn Xenon xung.',
					'Số lần nháy mỗi lần đo: 1 lần nháy.',
					'Tuổi thọ đèn: Hơn 1 triệu lần nháy.',
					'Thời gian đo: < 1 giây từ lúc nhấn nút đến khi hoàn tất đo, 2 giây từ lúc nhấn nút đến khi hiển thị dữ liệu.',
					'Khoảng cách tối thiểu giữa các lần đo: 3 giây.',
					'Tiêu chuẩn tuân thủ: CIE 15:2004, ISO 7724/1, ASTM E1164, DIN 5033, Teil 7 và JIS Z 8722 Điều kiện C.',
					'Độ truy vết tiêu chuẩn: Việc gán tiêu chuẩn của thiết bị tuân theo Viện Tiêu chuẩn và Công nghệ Quốc gia (NIST) dựa trên các phương pháp được mô tả trong CIE Publication 44 và ASTM E259.',
				],
			},
			{
				title: 'Hiệu suất',
				desc: [
					'Sự đồng nhất giữa các thiết bị đo màu (IIA):',
					'- ∆E*< 0.15 CIE L*a*b* (Avg) trên BCRA II Tile Set',
					'- ∆E*< 0.25 CIE L*a*b* (Max) trên BCRA II Tile Set',
					'Khả năng tái tạo màu: ∆E*< 0.05 CIE L*a*b* trên gạch trắng (20 Lần đo).',
				],
			},
			{
				title: 'Phần mềm tích hợp',
				desc: [
					'Dữ liệu hiển thị: Dữ liệu màu, Dữ liệu chênh lệch màu, Đồ thị màu ba kích thích, Dữ liệu quang phổ, Dữ liệu chênh lệch quang phổ, Đồ thị quang phổ, Đồ thị chênh lệch quang phổ.',
					'Chức năng USB Flash Drive: Sao lưu cấu hình và dữ liệu, Chuyển cấu hình đến nhiều thiết bị, Xuất dữ liệu ra Excel.',
					'Các tính năng khác: Đánh giá đạt/không đạt, Tính trung bình nhiều lần đo, Tìm tiêu chuẩn gần nhất.',
					'Nguồn sáng: A, C, D50, D55, D65, D75, F2, F7, F11.',
					'Góc quan sát: 2° và 10°.',
					'Thang màu: CIE L*a*b*, Hunter Lab, CIE L*C*h, CIE Yxy, CIE XYZ.',
					'Thang chênh lệch màu: ∆L*a*b*, ∆Lab, ∆L*C*H, ∆L*C*h, ∆Yxy, ∆XYZ.',
					'Chỉ số chênh lệch màu: ∆E*, ∆E, ∆C*, ∆C, ∆Ecmc.',
					'Chỉ số và thông số: Độ trắng và độ nhuốm màu E313 (C/2° hoặc D65/10°), Độ vàng E313 (C/2° hoặc D65/10°), Độ vàng D1925 (C/2°), Độ sáng Y, Z%, Độ sáng 457 nm, Độ đục, Độ bền màu (Trung bình và Bước sóng đơn), Thay đổi xám, Vết bẩn xám, Chỉ số Metamerism, Số màu.',
					'Ngôn ngữ: Tiếng Trung, Tiếng Anh, Tiếng Pháp, Tiếng Đức, Tiếng Ý, Tiếng Nhật, Tiếng Tây Ban Nha.',
				],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [
					'Kích thước cảm biến:',
					'- Chiều cao: 16 cm (6.3 in.)',
					'- Chiều rộng: 13 cm (5.1 in.)',
					'- Chiều sâu: 36 cm (14.2 in.)',
					'- Trọng lượng: 4.5 kg (9.9 lbs)',
					'- Màn hình hiển thị: Kích thước 7.1 cm x 5.4 cm (2.8 in. x 2.1 in.), màn hình LCD màu có đèn nền.',
					'Giao diện: Cổng kết nối: 3 cổng USB 2.0.',
					'Nguồn điện: Điện áp 100 đến 240 VAC, 47 đến 63 Hz.',
					'Môi trường hoạt động: Nhiệt độ hoạt động: 10° đến 40°C (50° đến 104°F), Độ ẩm hoạt động: 10% đến 90% RH, không ngưng tụ.',
					'Môi trường lưu trữ: Nhiệt độ lưu trữ: -20° đến 65°C (-5° đến 150°F), Độ ẩm lưu trữ: 10% đến 90% RH, không ngưng tụ.',
					'Phụ kiện tiêu chuẩn đi kèm:',
					'- Gạch trắng hiệu chuẩn của thiết bị.',
					'- Chứng chỉ truy vết.',
					'- Kính đen.',
					'- Gạch chẩn đoán màu xanh lá.',
					'- Bộ đổi nguồn AC đa năng.',
					'- Cáp giao diện máy tính.',
					'- USB flash drive.',
					'- Hướng dẫn sử dụng ColorFlex EZ.',
				],
			},
		],
		documents: [
			{
				title: 'ColorFlex EZ Brochure',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-brochure.pdf',
			},
			{
				title: 'ColorFlex EZ Specifications',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-specifications.pdf',
			},
			{
				title: "ColorFlex EZ User's Manual",
				href: 'https://www.hunterlab.com/media/documents/users_manual_for_colorflex_ez.pdf',
			},
			{
				title: 'ColorFlex EZ Supplemental Manual For EasyMatch QC',
				href: 'https://www.hunterlab.com/media/documents/Supplemental_Manual_for_EZMQC_Colorflex_EZ_17662_v1.2.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/colorflex-ez-large-screen-area.png',
			'https://www.hunterlab.com/media/original_images/colorflex-ez-large-area-view.png',
			'https://www.hunterlab.com/media/original_images/colorflex-ez-connection-ports.png',
		],
	},
	{
		id: '3',
		name: 'Máy Đo Màu Cho Cà Phê ColorFlex EZ Coffee',
		image: '/products/ColorFlex_EZ_Coffee_2.png',
		category: '1',
		industries: ['2'],
		desc: 'Máy đo màu ColorFlex EZ Coffee là một thiết bị đo màu cà phê rang xay, cà phê hạt sấy khô và cà phê bột hòa tan một cách chính xác và dễ sử dụng. Độ chính xác này đạt được bằng cách sử dụng góc 45º/0º, công nghệ đo lường duy nhất được chứng minh là đo màu theo cách mắt người nhìn thấy. ColorFlex EZ Coffee cung cấp dữ liệu đo lường cần thiết để đảm bảo chất lượng sản phẩm đồng nhất giữa các lô. Các thang màu cà phê được cung cấp trong phần mềm bao gồm: Chỉ số màu cà phê HunterLab (HCCI), Số SCAA và Phân loại độ rang SCAA. Ngoài khả năng đo màu cà phê chuyên dụng, ColorFlex EZ Coffee cũng có thể đo màu phản xạ của nhiều loại mẫu không phải cà phê – chất lỏng, chất bán rắn, bột và chất rắn sử dụng dữ liệu chỉ số màu Hunter L,a,b tiêu chuẩn và CIE Lab* màu sắc và phổ.',
		features: [
			'Bộ đầy đủ các tấm hiệu chuẩn và chuẩn đoán',
			'Tấm chuyên cho cà phê để kiểm tra hiệu suất',
			'1 hộp các đĩa mẫu cà phê bằng nhựa',
			'Được hỗ trợ bởi bộ phận hỗ trợ khách hàng tốt nhất trong ngành',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [
					'Nguyên lý đo: Máy quang phổ/máy đo màu để bàn hai chùm tia với thiết kế có thể sử dụng theo hai cách: hướng cổng lên trên hoặc hướng cổng về phía trước.',
					'Hình học đo: Chiếu sáng theo vòng tròn định hướng 45° / quan sát ở góc 0°.',
					'Máy quang phổ/máy đo màu: Hệ thống quang học kín; dãy diode 256 phần tử và lưới nhiễu xạ holographic lõm có độ phân giải cao.',
					'Đường kính cổng/Đường kính quan sát: 31,8 mm (1,25 inch) được chiếu sáng / 25,4 mm (1 inch) được đo.',
					'Thành phần phản xạ: Loại trừ.',
					'Dải quang phổ: 400 nm - 700 nm.',
					'Độ phân giải quang phổ: < 3 nm.',
					'Độ rộng dải hiệu dụng: 10 nm tương đương hình tam giác.',
					'Khoảng cách báo cáo: 10 nm.',
					'Phạm vi quang học: 0 đến 150%.',
					'Nguồn sáng: Đèn Xenon xung.',
					'Số lần nháy mỗi lần đo: 1 lần nháy.',
					'Tuổi thọ đèn: Hơn 1 triệu lần nháy.',
					'Thời gian đo: < 1 giây từ lúc nhấn nút đến khi hoàn tất đo, 2 giây từ lúc nhấn nút đến khi hiển thị dữ liệu.',
					'Khoảng cách tối thiểu giữa các lần đo: 3 giây.',
					'Tiêu chuẩn tuân thủ: CIE 15:2004, ISO 7724/1, ASTM E1164, DIN 5033, Teil 7 và JIS Z 8722 Điều kiện C.',
					'Độ truy vết tiêu chuẩn: tuân theo Viện Tiêu chuẩn và Công nghệ Quốc gia (NIST) dựa trên các phương pháp được mô tả trong CIE Publication 44 và ASTM E259.',
				],
			},
			{
				title: 'Hiệu suất',
				desc: [
					'Sự đồng nhất giữa các thiết bị đo màu (IIA):',
					'- ∆E*< 0.15 CIE L*a*b* (Avg) trên BCRA II Tile Set',
					'- ∆E*< 0.25 CIE L*a*b* (Max) trên BCRA II Tile Set',
					'Khả năng tái tạo màu: ∆E*< 0.05 CIE L*a*b* trên gạch trắng (20 Lần đo).',
				],
			},
			{
				title: 'Phần mềm tích hợp',
				desc: [
					'Dữ liệu hiển thị: Dữ liệu Cà Phê, Dữ liệu màu, Dữ liệu chênh lệch màu, Đồ thị màu ba kích thích, Dữ liệu quang phổ, Dữ liệu chênh lệch quang phổ, Đồ thị quang phổ, Đồ thị chênh lệch quang phổ.',
					'Chức năng USB Flash Drive: Sao lưu cấu hình và dữ liệu, Chuyển cấu hình đến nhiều thiết bị, Xuất dữ liệu ra Excel.',
					'Các tính năng khác: Đánh giá đạt/không đạt, Tính trung bình nhiều lần đo, Tìm tiêu chuẩn gần nhất.',
					'Nguồn sáng: A, C, D50, D55, D65, D75, F2, F7, F11.',
					'Góc quan sát: 2° và 10°.',
					'Thang màu: CIE L*a*b*, Hunter Lab, CIE L*C*h, CIE Yxy, CIE XYZ.',
					'Thang chênh lệch màu: ∆L*a*b*, ∆Lab, ∆L*C*H, ∆L*C*h, ∆Yxy, ∆XYZ.',
					'Chỉ số chênh lệch màu: ∆E*, ∆E, ∆C*, ∆C, ∆Ecmc.',
					'Chỉ số và thông số: Độ trắng và độ nhuốm màu E313 (C/2° hoặc D65/10°), Độ vàng E313 (C/2° hoặc D65/10°), Độ vàng D1925 (C/2°), Độ sáng Y, Z%, Độ sáng 457 nm, Độ đục, Độ bền màu (Trung bình và Bước sóng đơn), Thay đổi xám, Vết bẩn xám, Chỉ số Metamerism, Số màu.',
					'Ngôn ngữ: Tiếng Trung, Tiếng Anh, Tiếng Pháp, Tiếng Đức, Tiếng Ý, Tiếng Nhật, Tiếng Tây Ban Nha.',
				],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [
					'Kích thước cảm biến:',
					'- Chiều cao: 16 cm (6.3 in.)',
					'- Chiều rộng: 13 cm (5.1 in.)',
					'- Chiều sâu: 36 cm (14.2 in.)',
					'- Trọng lượng: 4.5 kg (9.9 lbs)',
					'- Màn hình hiển thị: Kích thước 7.1 cm x 5.4 cm (2.8 in. x 2.1 in.), màn hình LCD màu có đèn nền.',
					'Giao diện: Cổng kết nối: 3 cổng USB 2.0.',
					'Nguồn điện: Điện áp 100 đến 240 VAC, 47 đến 63 Hz.',
					'Môi trường hoạt động: Nhiệt độ hoạt động: 10° đến 40°C (50° đến 104°F), Độ ẩm hoạt động: 10% đến 90% RH, không ngưng tụ.',
					'Môi trường lưu trữ: Nhiệt độ lưu trữ: -20° đến 65°C (-5° đến 150°F), Độ ẩm lưu trữ: 10% đến 90% RH, không ngưng tụ.',
					'Phụ kiện tiêu chuẩn đi kèm:',
					'- Gạch trắng hiệu chuẩn của thiết bị.',
					'- Chứng chỉ truy vết.',
					'- Kính đen.',
					'- Gạch chẩn đoán màu xanh lá.',
					'- Bộ đổi nguồn AC đa năng.',
					'- Cáp giao diện máy tính.',
					'- USB flash drive.',
					'- Hướng dẫn sử dụng ColorFlex EZ.',
				],
			},
		],
		documents: [
			{
				title: 'ColorFlex EZ Coffee Brochure',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-coffee-brochure.pdf',
			},
			{
				title: 'ColorFlex EZ Coffee Technical Specifications',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-coffee-specifications.pdf',
			},
			{
				title: "ColorFlex EZ Coffee User's Manual",
				href: 'https://www.hunterlab.com/media/documents/users_manual_for_colorflex_ez_coffee.pdf',
			},
			{
				title: 'ColorFlex® EZ Coffee Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-coffee-quick-start-guide.pdf',
			},
			{
				title: 'ColorFlex EZ Supplemental Manual for EasyMatch QC',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-supplemental-manual-for-easymatch-qc.pdf',
			},
			{
				title: 'MEASUREMENT METHOD 5102 Measuring Ground Coffee with ColorFlex EZ Coffee',
				href: 'https://www.hunterlab.com/media/documents/mm-5102-measuring-ground-coffee-with-colorflex-ez-coffee-product.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/colorflex-ez-large-screen-area.png',
			'https://www.hunterlab.com/media/original_images/colorflex-ez-large-area-view.png',
			'https://www.hunterlab.com/media/original_images/colorflex-ez-connection-ports.png',
		],
	},
	{
		id: '4',
		name: 'Máy Đo Màu Quang Phổ ColorFlex EZ Citrus',
		image: '/products/ColorFlex_EZ_Citrus.png',
		category: '1',
		industries: ['2'],
		desc: 'Máy đo màu ColorFlex EZ Citrus dễ sử dụng được thiết kế đặc biệt để đo chính xác Citrus, Citrus Redness và Citrus Yellowness. Độ chính xác này đạt được bằng cách sử dụng hình học quang học 45º/0º, công nghệ đo lường duy nhất đã được chứng minh là đo màu theo cách mắt người nhìn thấy. Máy đo màu ColorFlex EZ Citrus bao gồm giá đỡ ống mẫu, giá đỡ đứng, kẹp và một O.J. bằng nhựa đã hiệu chuẩn. Thiết bị có màn hình lớn, dễ đọc và bàn phím kín. ColorFlex EZ Citrus chiếm rất ít không gian phòng thí nghiệm và rất dễ sử dụng. Trong thực tế, mẫu nước trái cây được đổ vào ống nghiệm hoặc ống có nắp đậy. Ống được lắp vào giá đỡ. Bằng cách nhấn một nút trên thiết bị, phép đo được thực hiện. CN (Citrus Number), CR (Citrus Redness) và CY (Citrus Yellowness) sẽ được hiển thị đồng thời. ColorFlex EZ Citrus có thể được kết nối với máy in nếu muốn in dữ liệu ra giấy.',
		features: [
			'Máy so màu phản xạ của chất rắn và chất lỏng',
			'Lưu trữ theo tiêu chuẩn sản phẩm với dung sai Pass / Fail',
			'Thiết bị để bàn nhỏ gọn',
			'Có thể được kết nối với máy in hoặc PC',
			'Tương thích với phần mềm EasyMatch',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [
					'Nguyên lý đo: Máy quang phổ/máy đo màu để bàn hai chùm tia với thiết kế có thể sử dụng theo hai cách: hướng cổng lên trên hoặc hướng cổng về phía trước.',
					'Hình học đo: Chiếu sáng theo vòng tròn định hướng 45° / quan sát ở góc 0°.',
					'Máy quang phổ/máy đo màu: Hệ thống quang học kín; dãy diode 256 phần tử và lưới nhiễu xạ holographic lõm có độ phân giải cao.',
					'Đường kính cổng/Đường kính quan sát: 31,8 mm (1,25 inch) được chiếu sáng / 25,4 mm (1 inch) được đo.',
					'Thành phần phản xạ: Loại trừ.',
					'Dải quang phổ: 400 nm - 700 nm.',
					'Độ phân giải quang phổ: < 3 nm.',
					'Độ rộng dải hiệu dụng: 10 nm tương đương hình tam giác.',
					'Khoảng cách báo cáo: 10 nm.',
					'Phạm vi quang học: 0 đến 150%.',
					'Nguồn sáng: Đèn Xenon xung.',
					'Số lần nháy mỗi lần đo: 1 lần nháy.',
					'Tuổi thọ đèn: Hơn 1 triệu lần nháy.',
					'Thời gian đo: < 1 giây từ lúc nhấn nút đến khi hoàn tất đo, 2 giây từ lúc nhấn nút đến khi hiển thị dữ liệu.',
					'Khoảng cách tối thiểu giữa các lần đo: 3 giây.',
					'Tiêu chuẩn tuân thủ: CIE 15:2004, ISO 7724/1, ASTM E1164, DIN 5033, Teil 7 và JIS Z 8722 Điều kiện C.',
					'Độ truy vết tiêu chuẩn: tuân theo Viện Tiêu chuẩn và Công nghệ Quốc gia (NIST) dựa trên các phương pháp được mô tả trong CIE Publication 44 và ASTM E259.',
				],
			},
			{
				title: 'Hiệu suất',
				desc: [
					'Sự đồng nhất giữa các thiết bị đo màu (IIA):',
					'- ∆E*< 0.15 CIE L*a*b* (Avg) trên BCRA II Tile Set',
					'- ∆E*< 0.25 CIE L*a*b* (Max) trên BCRA II Tile Set',
					'Khả năng tái tạo màu: ∆E*< 0.05 CIE L*a*b* trên gạch trắng (20 Lần đo).',
				],
			},
			{
				title: 'Phần mềm tích hợp',
				desc: [
					'Dữ liệu hiển thị: Dữ liệu màu, Dữ liệu chênh lệch màu, Đồ thị màu ba kích thích, Dữ liệu quang phổ, Dữ liệu chênh lệch quang phổ, Đồ thị quang phổ, Đồ thị chênh lệch quang phổ.',
					'Chức năng USB Flash Drive: Sao lưu cấu hình và dữ liệu, Chuyển cấu hình đến nhiều thiết bị, Xuất dữ liệu ra Excel.',
					'Các tính năng khác: Đánh giá đạt/không đạt, Tính trung bình nhiều lần đo, Tìm tiêu chuẩn gần nhất.',
					'Nguồn sáng: A, C, D50, D55, D65, D75, F2, F7, F11.',
					'Góc quan sát: 2° và 10°.',
					'Thang màu: CIE L*a*b*, Hunter Lab, CIE LCh, CIE Yxy, CIE XYZ.',
					'Thang chênh lệch màu: ∆L*a*b*, ∆Lab, ∆L*C*H, ∆L*C*h, ∆Yxy, ∆XYZ.',
					'Chỉ số chênh lệch màu: ∆E*, ∆E, ∆C*, ∆C, ∆Ecmc.',
					'Chỉ số và thông số: Độ trắng và độ nhuốm màu E313 (C/2° hoặc D65/10°), Độ vàng E313 (C/2° hoặc D65/10°), Độ vàng D1925 (C/2°), Độ sáng Y, Z%, Độ sáng 457 nm, Độ đục, Độ bền màu (Trung bình và Bước sóng đơn), Thay đổi xám, Vết bẩn xám, Chỉ số Metamerism, Số màu.',
					'Chỉ số màu Citrus: Citrus Number, Citrus Redness và Citrus Yellowness Data Storage.',
					'Lưu trữ dữ liệu:',
					'- Dưới dạng tiêu chuẩn: Lưu trữ 250 dữ liệu quang phổ hoặc ba kích thích với dung sai đạt/không đạt, bao gồm Dữ liệu làm việc, Dữ liệu vật lý, Dữ liệu số và Dữ liệu Hitch.',
					'- Dưới dạng mẫu: Lưu trữ 2000 dữ liệu quang phổ.',
					'Ngôn ngữ: Tiếng Trung, Tiếng Anh, Tiếng Pháp, Tiếng Đức, Tiếng Ý, Tiếng Nhật, Tiếng Tây Ban Nha.',
				],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [
					'Kích thước cảm biến:',
					'- Chiều cao: 16 cm (6.3 in.)',
					'- Chiều rộng: 13 cm (5.1 in.)',
					'- Chiều sâu: 36 cm (14.2 in.)',
					'- Trọng lượng: 4.5 kg (9.9 lbs)',
					'- Màn hình hiển thị: Kích thước 7.1 cm x 5.4 cm (2.8 in. x 2.1 in.), màn hình LCD màu có đèn nền.',
					'Giao diện: Cổng kết nối: 3 cổng USB 2.0.',
					'Nguồn điện: Điện áp 100 đến 240 VAC, 47 đến 63 Hz.',
					'Môi trường hoạt động: Nhiệt độ hoạt động: 10° đến 40°C (50° đến 104°F), Độ ẩm hoạt động: 10% đến 90% RH, không ngưng tụ.',
					'Môi trường lưu trữ: Nhiệt độ lưu trữ: -20° đến 65°C (-5° đến 150°F), Độ ẩm lưu trữ: 10% đến 90% RH, không ngưng tụ.',
					'Phụ kiện tiêu chuẩn đi kèm:',
					'- Gạch trắng hiệu chuẩn của thiết bị.',
					'- Chứng chỉ truy vết.',
					'- Kính đen.',
					'- Gạch chẩn đoán màu xanh lá.',
					'- Bộ đổi nguồn AC đa năng.',
					'- Cáp giao diện máy tính.',
					'- USB flash drive.',
					'- Hướng dẫn sử dụng ColorFlex EZ.',
				],
			},
		],
		documents: [
			{
				title: 'ColorFlex EZ Citrus Brochure',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-citrus-brochure.pdf',
			},
			{
				title: 'ColorFlex EZ Citrus Technical Specifications',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-citrus-specifications.pdf',
			},
			{
				title: "ColorFlex EZ Citrus User's Manual",
				href: 'https://www.hunterlab.com/media/documents/users_manual_for_colorflex_ez_citrus.pdf',
			},
			{
				title: 'ColorFlex EZ Citrus Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-citrus-quick-start-guide.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/colorflex-ez-large-screen-area.png',
			'https://www.hunterlab.com/media/original_images/colorflex-ez-large-area-view.png',
			'https://www.hunterlab.com/media/original_images/colorflex-ez-connection-ports.png',
		],
	},
	{
		id: '5',
		name: 'Máy Đo Màu Quang Phổ ColorFlex EZ Tomato',
		image: '/products/ColorFlex_EZ_Tomato_3390_2_sauce.png',
		category: '1',
		industries: ['1', '2'],
		desc: 'Máy đo màu ColorFlex EZ Tomato là một thiết bị đo màu dễ sử dụng, được thiết kế đặc biệt để đo chính xác màu sắc của cà chua trong tất cả các dạng sản phẩm đã qua xử lý – bao gồm nước sốt cà chua, xốt cà chua, tương cà, nước ép và cả cà chua tươi. Độ chính xác này được đạt được bằng cách sử dụng hình học quang học 45º/0º, là công nghệ đo duy nhất được chứng minh là có thể đo được màu sắc theo cách mà mắt người nhìn thấy. Bên cạnh đó, phần mềm cũng cung cấp các chỉ số màu Hunter L, a, b và CIE Lab*, cho phép bạn sử dụng ColorFlex EZ Tomato của mình để đo màu phản chiếu của nhiều loại mẫu không phải cà chua – chất lỏng, chất bán rắn, bột và chất rắn. Với hộp đựng thiết bị đặc biệt, chống nước trong đó có đầy đủ các dụng cụ cần thiết để bắt đầu đo giá trị màu sắc của cà chua ngay lập tức.',
		features: [
			'Thiết bị đo màu phản chiếu của chất rắn và chất lỏng',
			'Lưu trữ sản phẩm theo tiêu chuẩn với dung sai đạt/không đạt',
			'Hiển thị dữ liệu màu sắc, biểu đồ màu sắc, dữ liệu phổ và biểu đồ phổ',
			'Đo đạc với hình học đo 45°/0°',
			'Chiếm rất ít diện tích trên bàn làm việc',
			'Có thể kết nối với máy in hoặc máy tính',
			'Tương thích với phần mềm kiểm soát chất lượng EasyMatch QC trên máy tính.',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [
					'Nguyên lý đo: Máy quang phổ/máy đo màu để bàn hai chùm tia với thiết kế có thể sử dụng theo hai cách: hướng cổng lên trên hoặc hướng cổng về phía trước.',
					'Hình học đo: Chiếu sáng theo vòng tròn định hướng 45° / quan sát ở góc 0°.',
					'Máy quang phổ/máy đo màu: Hệ thống quang học kín; dãy diode 256 phần tử và lưới nhiễu xạ holographic lõm có độ phân giải cao.',
					'Đường kính cổng/Đường kính quan sát: 31,8 mm (1,25 inch) được chiếu sáng / 25,4 mm (1 inch) được đo.',
					'Thành phần phản xạ: Loại trừ.',
					'Dải quang phổ: 400 nm - 700 nm.',
					'Độ phân giải quang phổ: < 3 nm.',
					'Độ rộng dải hiệu dụng: 10 nm tương đương hình tam giác.',
					'Khoảng cách báo cáo: 10 nm.',
					'Phạm vi quang học: 0 đến 150%.',
					'Nguồn sáng: Đèn Xenon xung.',
					'Số lần nháy mỗi lần đo: 1 lần nháy.',
					'Tuổi thọ đèn: Hơn 1 triệu lần nháy.',
					'Thời gian đo: < 1 giây từ lúc nhấn nút đến khi hoàn tất đo, 2 giây từ lúc nhấn nút đến khi hiển thị dữ liệu.',
					'Khoảng cách tối thiểu giữa các lần đo: 3 giây.',
					'Tiêu chuẩn tuân thủ: CIE 15:2004, ISO 7724/1, ASTM E1164, DIN 5033, Teil 7 và JIS Z 8722 Điều kiện C.',
					'Độ truy vết tiêu chuẩn: tuân theo Viện Tiêu chuẩn và Công nghệ Quốc gia (NIST) dựa trên các phương pháp được mô tả trong CIE Publication 44 và ASTM E259.',
				],
			},
			{
				title: 'Hiệu suất',
				desc: [
					'Sự đồng nhất giữa các thiết bị đo màu (IIA):',
					'- ∆E*< 0.15 CIE L*a*b* (Avg) trên BCRA II Tile Set',
					'- ∆E*< 0.25 CIE L*a*b* (Max) trên BCRA II Tile Set',
					'Khả năng tái tạo màu: ∆E*< 0.05 CIE L*a*b* trên gạch trắng (20 Lần đo).',
				],
			},
			{
				title: 'Phần mềm tích hợp',
				desc: [
					'Dữ liệu hiển thị: Dữ liệu màu, Dữ liệu chênh lệch màu, Đồ thị màu ba kích thích, Dữ liệu quang phổ, Dữ liệu chênh lệch quang phổ, Đồ thị quang phổ, Đồ thị chênh lệch quang phổ.',
					'Chức năng USB Flash Drive: Sao lưu cấu hình và dữ liệu, Chuyển cấu hình đến nhiều thiết bị, Xuất dữ liệu ra Excel.',
					'Các tính năng khác: Đánh giá đạt/không đạt, Tính trung bình nhiều lần đo, Tìm tiêu chuẩn gần nhất.',
					'Nguồn sáng: A, C, D50, D55, D65, D75, F2, F7, F11.',
					'Góc quan sát: 2° và 10°.',
					'Thang màu: CIE L*a*b*, Hunter Lab, CIE L*C*h, CIE Yxy, CIE XYZ.',
					'Thang chênh lệch màu: ∆L*a*b*, ∆Lab, ∆L*C*H, ∆L*C*h, ∆Yxy, ∆XYZ.',
					'Chỉ số chênh lệch màu: ∆E*, ∆E, ∆C*, ∆C, ∆Ecmc.',
					'Chỉ số và thông số: Độ trắng và độ nhuốm màu E313 (C/2° hoặc D65/10°), Độ vàng E313 (C/2° hoặc D65/10°), Độ vàng D1925 (C/2°), Độ sáng Y, Z%, Độ sáng 457 nm, Độ đục, Độ bền màu (Trung bình và Bước sóng đơn), Thay đổi xám, Vết bẩn xám, Chỉ số Metamerism, Số màu.',
					'Chỉ số cà chua:',
					'- TPS - Điểm số cà chua cô đặc',
					'- TSS - Điểm số sốt cà chua',
					'- TCS - Điểm số tương cà',
					'- TJS - Điểm số nước ép cà chua',
					'- Tỷ lệ a/b của cà chua',
					'- Chỉ số Lycopene',
					'Ngôn ngữ: Tiếng Trung, Tiếng Anh, Tiếng Pháp, Tiếng Đức, Tiếng Ý, Tiếng Nhật, Tiếng Tây Ban Nha.',
				],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [
					'Kích thước cảm biến:',
					'- Chiều cao: 16 cm (6.3 in.)',
					'- Chiều rộng: 13 cm (5.1 in.)',
					'- Chiều sâu: 36 cm (14.2 in.)',
					'- Trọng lượng: 4.5 kg (9.9 lbs)',
					'- Màn hình hiển thị: Kích thước 7.1 cm x 5.4 cm (2.8 in. x 2.1 in.), màn hình LCD màu có đèn nền.',
					'Giao diện: Cổng kết nối: 3 cổng USB 2.0.',
					'Nguồn điện: Điện áp 100 đến 240 VAC, 47 đến 63 Hz.',
					'Môi trường hoạt động: Nhiệt độ hoạt động: 10° đến 40°C (50° đến 104°F), Độ ẩm hoạt động: 10% đến 90% RH, không ngưng tụ.',
					'Môi trường lưu trữ: Nhiệt độ lưu trữ: -20° đến 65°C (-5° đến 150°F), Độ ẩm lưu trữ: 10% đến 90% RH, không ngưng tụ.',
					'Phụ kiện tiêu chuẩn đi kèm:',
					'- Gạch trắng hiệu chuẩn của thiết bị.',
					'- Chứng chỉ truy vết.',
					'- Kính đen.',
					'- Gạch chẩn đoán màu xanh lá.',
					'- Bộ đổi nguồn AC đa năng.',
					'- Cáp giao diện máy tính.',
					'- USB flash drive.',
					'- Hướng dẫn sử dụng ColorFlex EZ.',
				],
			},
		],
		documents: [
			{
				title: 'ColorFlex EZ Tomato Brochure',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-tomato-brochure-us.pdf',
			},
			{
				title: 'ColorFlex EZ Tomato Technical Specifications',
				href: 'https://www.hunterlab.com/media/documents/colorflex-ez-tomato-specifications.pdf',
			},
			{
				title: "ColorFlex EZ Tomato User's Manual",
				href: 'https://www.hunterlab.com/media/documents/users_manual_for_colorflex_ez_tomato.pdf',
			},
			{
				title: 'ColorFlex EZ Tomato Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/colorflex-tomato-quick-start-guide.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/colorflex-ez-large-screen-area.png',
			'https://www.hunterlab.com/media/original_images/colorflex-ez-large-area-view.png',
			'https://www.hunterlab.com/media/original_images/colorflex-ez-connection-ports.png',
		],
	},
	{
		id: '6',
		name: 'Máy Đo Màu Quang Phổ Hunterlab Aeros',
		image: '/products/aeros-spectrophotometer.png',
		category: '1',
		industries: ['1', '2', '4', '5', '6'],
		desc: 'Máy đo màu quang phổ Aeros của HunterLab với các tính năng cải tiến mới như định vị chiều cao tự động, đế đặt mẫu xoay, màn hình cảm ứng lớn và thông tin liên lạc thông minh. Aeros là cách tốt nhất để bạn đo màu của mẫu có hình dạng, kết cấu bất thường. Aeros có thể xử lý một cách nhanh chóng các sản phẩm như hạt cà phê, snacks, viên nhựa, thuốc viên, thậm chí cả khoáng chất công nghiệp. Kết hợp phương pháp đo lường không tiếp xúc đang chờ cấp bằng sáng chế với định vị độ cao tự động, đế đặt mẫu xoay và EasyMatch Essentials® – phần mềm kiểm soát chất lượng màu độc quyền của HunterLab cung cấp tất cả các chỉ số màu và số liệu bạn cần – Aeros là máy so màu thông minh và hoàn chỉnh.',
		features: [
			'Được thiết kế cho các mẫu có nhiều kết cấu, không đồng nhất',
			'Cảm biến tự động định vị chiều cao và không tiếp xúc',
			'Bệ mẫu xoay, lớn nhất trong ngành',
			'5 giây, 35 phép đo, 27,5 inch vuông mẫu được đo',
			'Màn hình cảm ứng với giao diện người dùng hiện đại',
			'Kết nối USB và Ethernet',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [
					'Nguyên lý đo: Máy quang phổ/máy đo màu phản xạ không tiếp xúc hai chùm tia.',
					'Phương pháp đo: Hướng cổng xuống; không tiếp xúc; bàn xoay.',
					'Chiều cao mẫu tối đa: 140 mm (5.5 in.).',
					'Thời gian đo: Có thể lựa chọn (5, 10, 15, 30 giây).',
					'Tốc độ lấy mẫu: 7 lần đo mỗi giây.',
					'Số lượng phép đo mỗi vòng quay: 35.',
					'Diện tích đo mỗi vòng quay: 177,25 cm² (27,5 in²).',
				],
			},
			{
				title: 'Thông số kỹ thuật',
				desc: [
					'Phạm vi quang phổ: 400 nm - 700 nm.',
					'Thành phần ánh sáng gương: Bị loại trừ.',
					'Độ phân giải phổ: < 3 nm.',
					'Băng thông hiệu dụng: 10 nm tam giác tương đương.',
					'Khoảng thời gian báo cáo: 10 nm.',
					'Phạm vi đo quang: 0 đến 150 %.',
					'Nguồn sáng: Dãy đèn LED cân bằng toàn phổ.',
					'Tuổi thọ đèn LED: 5 năm (thông thường).',
					'Máy đo quang phổ: Quang học kín; dãy diode 256 phần tử; lưới ánh sáng hội tụ lõm độ phân giải cao.',
					'Độ phân giải màn hình hiển thị: 0,1 mm.',
				],
			},
			{
				title: 'Hiệu suất',
				desc: [
					'Sự đồng nhất giữa các thiết bị đo màu (IIA): ΔE* < 0.30 (Trung bình) trên bộ gạch CCSII (CERAM).',
					'Khả năng tái tạo: ΔE*< 0.025 (Tối đa) trên gạch trắng.',
				],
			},
			{
				title: 'Giao diện người dùng',
				desc: [
					'Chế độ xem dữ liệu: EZ View, Bảng dữ liệu màu, Bảng dữ liệu phổ, Biểu đồ xu hướng.',
					'Các tính năng khác: Chỉ báo Pass/Fail (Đạt/KHÔNG Đạt), ghi nhãn và dấu thời gian, tự động đặt tên, tự động lưu, sao lưu và khôi phục dữ liệu.',
					'Các chỉ số và thông số đo: Chỉ số độ trắng E313, Độ nhạt màu, Chỉ số độ vàng E313, Chỉ số độ vàng D1925, Độ sáng Y, Tỷ lệ Z%, Độ sáng ở 457 nm, Đơn vị tương phản, HCCI, SCAA, ASTM E1349, Độ bóng: ASTM D523, ASTM D2457, ISO 2813, ISO 7668, JIS Z 8741.',
					'Thang màu: CIE L*a*b*, Hunter Lab, CIE LCh, CIE XYZ.',
					'Chỉ số khác biệt màu: ΔL*, ΔE*, ΔC*, ΔH*, ΔXYY, AXYZ.',
					'Các chỉ số khác biệt màu: ΔE*, ΔE*CMC, ΔE 2000.',
					'Lưu trữ dữ liệu: 8 GB (> 1 triệu bản ghi dữ liệu với hình ảnh).',
					'Các nguồn sáng: A, C, D50, D65, D75, F02, F07, F11.',
					'Quan sát viên: 2° và 10°.',
					'Ngôn ngữ: Tiếng Anh, Tiếng Nhật và Tiếng Trung (Giản thể).',
					'Hiển thị: Màn hình cảm ứng, độ phân giải cao 1280x800.',
					'Phần mềm PC ngoài: Tương thích với HunterLab EasyMatch QC và Phần mềm Kiểm soát Chất lượng Dữ liệu Điện tử EasyMatch QC.',
				],
			},
			{
				title: 'Kết Nối I/O',
				desc: [
					'USB OTG: Kết nối với máy in, bàn phím, chuột.',
					'Cổng USB phía trước: Chuẩn 2.0 hai chiều, xuất/nhập dữ liệu qua ổ đĩa USB.',
					'Ethernet RJ45: In trực tiếp đến các máy in độc lập hoặc trên mạng, Gửi email trực tiếp từ thiết bị, Truyền dữ liệu đến hệ thống LIMS và SPC.',
					'Đầu vào ngoài: Công tắc chân từ xa hoặc thiết bị chuyển đổi tiếp xúc kín tương tự.',
					'Hỗ trợ truy cập từ xa: Kích hoạt thông qua công cụ hỗ trợ dựa trên internet.',
				],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [
					'Kích thước cảm biến:',
					'- Chiều cao: 56 cm (22 in)',
					'- Chiều rộng: 38 cm (15 in)',
					'- Chiều sâu: 51 cm (20 in)',
					'- Trọng lượng: 23 kg (50 lbs)',
					'- Màn hình: Màn hình cảm ứng điện dung, độ phân giải cao, màu sắc, kích thước 17.8 cm (7 in), 1280 x 800',
					'Nguồn điện: Đầu vào từ 100 đến 240 VAC, 47 đến 63 Hz cho nguồn cấp điện phổ thông @ 24 VDC (3.75A 90W)',
					'Môi trường hoạt động: Nhiệt độ 4° đến 38° C (40° đến 100° F), Độ ẩm 10 % đến 85 % RH, không ngưng tụ',
					'Môi trường lưu trữ: Nhiệt độ -20° đến 65° C (-5° đến 150° F), độ ẩm 10 % đến 90 % RH, không ngưng tụ',
					'Các thành phần hệ thống:',
					'- Gạch trắng hiệu chuẩn (Chứng nhận độ truy xuất nguồn gốc của NIST).',
					'- Tiêu chuẩn kính đen.',
					'- Gạch chẩn đoán màu xanh lá cây.',
					'- Hộp tiêu chuẩn.',
					'- Khay 15.2 cm (6 in) / Độ sâu 2.54 cm (1 in).',
					'- Khay 30.5 cm (12 in) / Độ sâu 2.54 cm (1 in).',
					'- Nguồn điện đa năng 100V - 240V.',
					'- Hướng dẫn khởi động nhanh Aeros.',
					'- Hướng dẫn sử dụng Aeros trên CD.',
				],
			},
		],
		documents: [
			{
				title: 'Aeros Brochure',
				href: 'https://www.hunterlab.com/media/documents/Aeros_Brochure.pdf',
			},
			{
				title: 'Aeros User Manual',
				href: 'https://www.hunterlab.com/media/documents/Users_Manual_for_Aeros_A60-1018-193_2.0.pdf',
			},
			{
				title: 'Aeros Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/aeros-quick-start-guide.pdf',
			},
			{
				title: 'Aeros Specifications',
				href: 'https://www.hunterlab.com/media/documents/Aeros_Specifications.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/aeros-standardization.png',
			'https://www.hunterlab.com/media/original_images/aeros-color-data-table.png',
			'https://www.hunterlab.com/media/original_images/aeros-connection-ports.png',
		],
	},
	{
		id: '7',
		name: 'Máy Đo Màu Quang Phổ Hunterlab Vista',
		image: '/products/vista-spectrophotometer.png',
		category: '1',
		industries: ['1', '2', '3', '4'],
		desc: 'Vista® là máy đo màu quang phổ truyền ánh sáng khả kiến giàu tính năng, nhỏ gọn đo được cùng lúc màu sắc và độ mù của những mẫu trong suốt/trong mờ. Máy đo màu quang phổ truyền ánh sáng khả kiến giàu tính năng, nhỏ gọn đo được cùng lúc màu sắc và độ mù của những mẫu trong suốt/trong mờ. Được thiết kế nhằm đáp ứng nhu cầu của người dùng về tính đơn giản, sự chính xác, độ tin cậy và giá cả hợp lý, Vista có khả năng đo màu sắc và độ mù của nhiều loại mẫu trong một phép đo dễ dàng, trong khi vẫn cung cấp cho người dùng một giao diện trực quan và dễ sử dụng.',
		features: [
			'Đo màu chính xác và nhất quán giúp kiểm tra chất lượng dễ dàng',
			'Tạo ra các chuẩn mực tiêu chuẩn để đáp ứng các mục tiêu đảm bảo chất lượng',
			'Phát hiện nhiễm bẩn trong nguyên liệu thô ngay từ đầu',
			'Kích thước nhỏ gọn',
			'Cung cấp các sản phẩm chất lượng cao một cách nhất quán',
			'In, gửi email hoặc phát trực tuyến dữ liệu đo lường (LIMS và SPC)',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [
					'Nguyên lý đo: Máy quang phổ/máy đo màu phản xạ tiếp xúc hai chùm tia.',
					'Hình học: Tt/0º hoặc Td/0º theo tiêu chuẩn ASTM 1164, CIE 15:2018',
					'Quang phổ kế/Máy đo màu: Dãy diode 256 phần tử và lưới ánh sáng hội tụ lõm độ phân giải cao',
					'Kích thước cổng/Khu vực đo: 10.5 mm (0.41 in) chiếu sáng/9.8 mm (0.39 in) được đo',
					'Thời gian đo: 2.5 giây',
					'Thời gian đo với Haze: 5 giây',
					'Khoảng thời gian đo: tối thiểu 3 giây',
					'Chiều dài đường đo: Lên đến 100 mm',
					'Chế độ truyền: Tổng (TTRAN), Thường (RTRAN) và Haze',
					'Tuân thủ tiêu chuẩn:',
					'- Màu sắc: CIE 15:2018, ASTM E1164, DIN 5033 Phần 7 và JIS Z 8741 Điều kiện E, G',
					'- Haze: ASTM D1003',
				],
			},
			{
				title: 'Thông số kỹ thuật',
				desc: [
					'Đường kính cầu: 76 mm (3 in)',
					'Lớp phủ bên trong cầu: Spectralon™',
					'Phạm vi quang phổ: 400 nm - 700 nm',
					'Độ phân giải bước sóng: < 3 nm',
					'Băng thông hiệu dụng: 10 nm tam giác tương đương',
					'Khoảng thời gian báo cáo: 10 nm',
					'Phạm vi quang học: 0 đến 150 %',
					'Độ phân giải quang học: 0.003 % (0.01 % được báo cáo)',
					'Nguồn sáng: Dãy đèn LED toàn phổ',
					'Số lần phát sáng mỗi phép đo: 4 lần phát sáng',
					'Tuổi thọ đèn LED: 5 năm (thông thường)',
				],
			},
			{
				title: 'Hiệu suất',
				desc: [
					'Độ lặp lại màu sắc (tối đa 30 lần đo): < 0.02 ∆E* trong không khí',
					'Độ lặp lại phổ: Độ lệch chuẩn trong khoảng 0.1 %',
					'Sự đồng thuận giữa các thiết bị:',
					'- ∆E* (D65/10) < 0.15 (Trung bình) (Bộ lọc truyền)',
					'- ∆E* (D65/10) < 0.25 (Tối đa) (Bộ lọc truyền)',
					'- ± 0.30% tại 10% TH (HAZE)',
				],
			},
			{
				title: 'Giao diện người dùng',
				desc: [
					'Chế độ xem dữ liệu: EZ View, Bảng dữ liệu màu, Bảng dữ liệu phổ, Biểu đồ xu hướng.',
					'Các tính năng khác: Chỉ báo Pass/Fail (Đạt/KHÔNG Đạt), ghi nhãn và dấu thời gian, tự động đặt tên, tự động lưu, sao lưu và khôi phục dữ liệu.',
					'Các chỉ số và thông số đo: APHA/PtCo/Hazen, ADMI, Saybolt, Gardner, ASTM D1500, Iodine, ICUMSA, EBC, ASBC, ASBC Turbidity, Chinese Acid Wash, Lovibond® RYBN, AOCS RY, FAC, YI E313 Yellowness, YI D1925, WI E313, CIE Y Transmission, US Pharmacopeia, Japanese Pharmacopeia, Chinese Pharmacopeia, EU Pharmacopeia, EP Opalescence, Haze, NTU.',
					'Thang màu: CIE  L*a*b*, Hunter Lab, CIE LCh, CIE XYZ.',
					'Chỉ số khác biệt màu: ΔL*, ΔE*, ΔC*, ΔH*, ΔXYY, AXYZ.',
					'Các chỉ số khác biệt màu: ΔE*, ΔE*CMC, ΔE 2000.',
					'Lưu trữ dữ liệu: 8 GB (> 1 triệu bản ghi dữ liệu với hình ảnh).',
					'Các nguồn sáng: D65, C, A, D50, D55, D75, F02, F07, F11, TL84, ULT30, ULT35.',
					'Quan sát viên: 2° và 10°.',
					'Ngôn ngữ: Tiếng Anh, Tiếng Nhật và Tiếng Trung (Giản thể).',
					'Hiển thị: Màn hình cảm ứng, độ phân giải cao 1280x800.',
					'Phần mềm PC ngoài: Tương thích với HunterLab EasyMatch QC và Phần mềm Kiểm soát Chất lượng Dữ liệu Điện tử EasyMatch QC.',
				],
			},
			{
				title: 'Kết Nối I/O',
				desc: [
					'USB OTG: Kết nối với máy in, bàn phím, chuột.',
					'Cổng USB phía trước: Chuẩn 2.0 hai chiều, xuất/nhập dữ liệu qua ổ đĩa USB',
					'Ethernet RJ45: In trực tiếp đến các máy in độc lập hoặc trên mạng, Gửi email trực tiếp từ thiết bị, Truyền dữ liệu đến hệ thống LIMS và SPC',
					'Đầu vào ngoài: Công tắc chân từ xa hoặc thiết bị chuyển đổi tiếp xúc kín tương tự',
					'Hỗ trợ truy cập từ xa: Kích hoạt thông qua công cụ hỗ trợ dựa trên internet',
				],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [
					'Kích thước:',
					'- Chiều cao: 177.8 mm (7.0 in.)',
					'- Chiều rộng: 485.8 mm (19.125 in.)',
					'- Chiều sâu: 228.6 mm (9.0 in.)',
					'- Trọng lượng: 6.35 kg (14.0 lbs)',
					'Khoang truyền dẫn:',
					'- Chiều cao: 108.0 mm (4.25 in.)*',
					'- Chiều rộng: 101.6 mm (4.0 in.)',
					'- Chiều sâu: 187.3 mm (7.375 in.) với nắp đậy* (Nắp đậy có thể tháo rời, mở khoang ở ba phía (trên, trước, sau) để chứa các mẫu lớn).',
					'Khoảng cách từ đế đến cổng đo: 63.5 mm (2.5 in.)',
					'Yêu cầu về nguồn điện: Điện áp 100 đến 240 VAC, 47 đến 63 Hz, 60 W',
					'Môi trường hoạt động: Nhiệt độ 10 đến 40° C (50 đến 104º F), Độ ẩm 10 % đến 90 % RH, không ngưng tụ',
					'Môi trường lưu trữ: Nhiệt độ -21 đến 66° C (-5 đến 150º F), Độ ẩm: 10 % đến 90 % RH, không ngưng tụ',
					'Phụ kiện tiêu chuẩn:',
					'- Bộ lọc chẩn đoán Didymium',
					'- Giấy chứng nhận tuân thủ',
					'- Nguồn điện',
					'- Hướng dẫn khởi động nhanh VISTA',
					'- Bút cảm ứng',
					'- USB Flash Drive',
					'- Khăn lau',
				],
			},
		],
		documents: [
			{
				title: 'Vista Specifications',
				href: 'https://www.hunterlab.com/media/documents/Vista_Specifications.pdf',
			},
			{
				title: 'Vista User Manual',
				href: 'https://www.hunterlab.com/media/documents/Users_Manual_for_Vista_Essentials_ver_3.8_A60-1017-433.pdf',
			},
			{
				title: 'Vista Brochure',
				href: 'https://www.hunterlab.com/media/documents/Vista_Brochure_US_Letter_Final.pdf',
			},
			{
				title: 'Vista Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/vista-quick-start-guide.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/vista-product-feature-3.png',
			'https://www.hunterlab.com/media/original_images/vista-product-feature-2.png',
			'https://www.hunterlab.com/media/original_images/vista-product-feature-1.png',
		],
	},
	{
		id: '8',
		name: 'Máy Đo Màu Quang Phổ UltraScan PRO',
		image: '/products/ultrascan-pro-spectrophotometer.png',
		category: '1',
		industries: ['3', '6', '9'],
		desc: 'UltraScan® PRO là máy đo màu quang phổ tham chiếu chuẩn so với tất cả các loại khác được so sánh, lý tưởng cho các ứng dụng nghiên cứu và kiểm soát chất lượng. UltraScan® PRO đo các màu phản xạ và truyền đi, cũng như độ phản xạ quang phổ, độ truyền quang phổ và phủ mờ. Nó đáp ứng tất cả các hướng dẫn đo màu của CIE, ASTM và USP. Máy đo màu quang phổ UltraScan PRO đo quang phổ chính xác và độ ổn định lâu dài vượt trội, cung cấp phép đo màu chính xác và đáng tin cậy từ chất rắn đục đến chất lỏng trong suốt đến màng trong suốt.',
		features: [
			'Phạm vi bước sóng 350 nm – 1050nm',
			'Độ phân giải quang học 5nm',
			'Ba khu vực đo lường phản xạ',
			'Kiểm soát và hiệu chỉnh UV tự động',
			'Khoang truyền lớn mở ra ba phía',
			'Bao gồm phần mềm EasyMatch QC',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [
					'Nguyên lý đo lường: Máy quang phổ/máy đo màu hai chùm tia',
					'Hình học: Phản xạ khuếch tán d/8°, truyền dẫn tổng thể d/8°, truyền dẫn thông thường d/0°',
					'Máy quang phổ/Máy đo màu: Hai bộ tán sắc, mỗi bộ có mảng diode 512 phần tử và lưới nhiễu xạ lõm, độ phân giải cao',
					'Đường kính quả cầu: 152 mm (6 in.)',
					'Lớp phủ quả cầu: Spectraflect™ cho quả cầu, Duraflect™ cho tấm cổng và cửa loại bỏ gương',
					'Kích thước cổng/Khu vực đo:',
					'- Đường kính cổng/Đường kính vùng nhìn trong các chế độ phản xạ RSIN/RSEX',
					'+ Chế độ nhìn vùng lớn (LAV): Chiếu sáng 25 mm (1 in)/Đo 19 mm (0.75 in)',
					'+ Chế độ nhìn vùng trung bình (MAV): Chiếu sáng 13 mm (0.5 in)/Đo 9 mm (0.35 in)',
					'+ Chế độ nhìn vùng nhỏ (SAV): Chiếu sáng 7 mm (0.25 in)/Đo 4 mm (0.16 in)',
					'- Đường kính cổng/Đường kính vùng nhìn trong các chế độ truyền dẫn TTRAN',
					'+ Chế độ nhìn vùng lớn (LAV): Chiếu sáng 25 mm (1 in)/Đo 17.4 mm (0.69 in)',
					'+ Chế độ nhìn vùng trung bình (MAV): Chiếu sáng 25 mm (1 in)/Đo 13.2 mm (0.52 in)',
					'+ Chế độ nhìn vùng nhỏ (SAV): Chiếu sáng 25 mm (1 in)/Đo 11.6 mm (0.46 in)',
					'- Đường kính cổng/Đường kính vùng nhìn trong chế độ truyền dẫn RTRAN nơi ống kính là trường nhìn cho tất cả các khu vực',
					'+ Chế độ nhìn vùng lớn (LAV): Chiếu sáng 17 mm (0.67 in)/Đo 17 mm (0.67 in)',
					'+ Chế độ nhìn vùng trung bình (MAV): Chiếu sáng 17 mm (0.67 in)/Đo 17 mm (0.67 in)',
					'+ Chế độ nhìn vùng nhỏ (SAV): Chiếu sáng 17 mm (0.67 in)/Đo 17 mm (0.67 in)',
				],
			},
			{
				title: 'Thông số kỹ thuật',
				desc: [
					'Thành phần phản xạ: Tự động bao gồm (RSIN) hoặc loại trừ (RSEX) trong phản xạ',
					'Dải quang phổ: 350 nm - 1050 nm, bao gồm toàn bộ dải nhìn thấy theo CIE và phần hồng ngoại gần (NIR)',
					'Độ phân giải bước sóng: < 2 nm',
					'Băng thông hiệu dụng: 5 nm, tương đương hình tam giác',
					'Khoảng báo cáo: 5 nm',
					'Dải quang phổ đo: 0-150%',
					'Nguồn sáng: Đèn Xenon xung (3 bóng), được hiệu chuẩn và kiểm soát trong dải UV',
					'Kiểm soát UV tự động:',
					'- Bộ lọc cắt 400 nm để kiểm soát và loại trừ UV',
					'- Tùy chọn bộ lọc cắt 420 nm để loại trừ UV',
					'Chế độ truyền dẫn: Tổng thể (TTRAN) và Thông thường (RTRAN)',
					'Khoang truyền dẫn:',
					'- Lớn và mở ở 3 mặt',
					'- Kích thước: 10,2 cm sâu x 35,6 cm rộng x 16,5 cm cao (4 in. sâu x 14 in. rộng x 6,5 in. cao)',
					'Tuân thủ tiêu chuẩn:',
					'- Phản xạ: CIE 15:2004, ISO 7724/1, ASTM E1164, DIN 5033, Phần 7 và JIS Z 8722 Điều kiện C',
					'- Truyền dẫn: CIE 15:2004, ASTM E1164, DIN 5033 Phần 7 và JIS Z 8722 Điều kiện E, G Độ mờ tuân thủ theo ASTM D1003 Mục 8, Quy trình B',
				],
			},
			{
				title: 'Hiệu suất',
				desc: [
					'Sự đồng nhất giữa các thiết bị đo màu (IIA):',
					'- ∆E*< 0.09 CIE L*a*b* (Trung bình) trên bộ gạch BCRA II',
					'- ∆E*< 0.20 CIE L*a*b* (Tối đa) trên bộ gạch BCRA II',
					'Khả năng tái tạo (20 Lần đo):',
					'- < 0,03 ∆E* CIE L*a*b * trên ô màu trắng ở chế độ LAV',
					'- < 0,07 ∆E* CIE L*a*b* trên ô denim màu xanh ở chế độ LAV',
					'- Độ lặp lại quang phổ: Phạm vi tối đa 0,20 trong khoảng từ 435 nm đến 695 nm',
				],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [
					'Kích thước:',
					'- Chiều cao: 32,3 cm (12,7 in.)',
					'- Chiều rộng: 42,0 cm (16,5 in.)',
					'- Độ sâu: 49,8 cm (19,6 in.)',
					'- Trọng lượng: 25,9 kg (57 lbs)',
					'Nguồn điện:',
					'- 90 đến 250 VAC, 50 đến 60 Hz',
					'- 60 watts khi ở trạng thái chờ, 120 watts tối đa',
					'Giao diện: Cổng nối tiếp RS-232C, tốc độ 19.200 baud, đầu cắm DB9 (cổng cái)',
					'Môi trường vận hành: Nhiệt độ từ 4° đến 38°C (40° đến 100°F), độ ẩm 10% đến 85%, không ngưng tụ',
					'Môi trường lưu trữ: Nhiệt độ từ -21° đến 66°C (-5° đến 150°F), độ ẩm 10% đến 90%, không ngưng tụ',
					'Phụ kiện tiêu chuẩn:',
					'- Tấm chuẩn trắng được hiệu chuẩn',
					'- Chứng chỉ truy xuất nguồn gốc',
					'- Bẫy ánh sáng hiệu chuẩn màu đen',
					'- Tấm hiệu chuẩn không truyền dẫn',
					'- Tấm chẩn đoán màu xanh lá',
					'- Bộ lọc chẩn đoán bước sóng',
					'- Tiêu chuẩn huỳnh quang',
					'- Kẹp mẫu phản xạ',
					'- Khẩu độ LAV (vùng lớn)',
					'- Khẩu độ MAV (vùng trung bình)',
					'- Khẩu độ SAV (vùng nhỏ)',
					'- Cáp RS-232C',
					'- Bộ chuyển đổi USB sang Serial',
					'- Dây nguồn',
					'- Phần mềm EasyMatch QC',
					'- Sổ tay cơ bản EasyMatch QC',
				],
			},
		],
		documents: [
			{
				title: 'UltraScan PRO Brochure',
				href: 'https://www.hunterlab.com/media/documents/ultrascan-pro-brochure.pdf',
			},
			{
				title: 'UltraScan PRO Specifications',
				href: 'https://www.hunterlab.com/media/documents/ultrascan-pro-specifications.pdf',
			},
			{
				title: 'UltraScan PRO Supplemental Manual for EasyMatch QC',
				href: 'https://www.hunterlab.com/media/documents/Supplemental_Manual_for_EZMQC_UltraScan_PRO.pdf',
			},
		],
		assets: [],
	},
	{
		id: '9',
		name: 'Máy Đo Màu Di Động MiniScan EZ 4500',
		image: '/products/miniscan-ez-spectrophotometer.png',
		category: '2',
		industries: ['1', '3', '6', '7', '8', '9'],
		desc: 'Máy đo màu di động MiniScan EZ 4500 có thiết kế 45 ° / 0 ° với màn hình lớn, trọng lượng nhẹ và được thiết kế công thái học để thao tác bằng một tay. Với phần mềm tích hợp bao gồm hầu hết các thang màu và chỉ số phản xạ công nghiệp chính. MiniScan EZ 4500 cho phép các nhà sản xuất đánh giá dễ dàng và chính xác chất lượng sản phẩm của mình.Hình học 45 ° / 0 ° với chế độ xem khu vực rộng lớn.',
		features: [
			'Trọng lượng nhẹ với tay cầm bọc cao su tạo sự thoải mái cho người vận hành',
			'Thao tác dễ dàng bằng một tay, điều hướng bằng đầu ngón tay cái của các chức năng',
			'Màn hình LCD lớn, dễ đọc',
			'Hiển thị dữ liệu màu, dữ liệu chênh lệch màu, biểu đồ màu, dữ liệu quang phổ, chênh lệch dữ liệu quang phổ, biểu đồ quang phổ, biểu đồ chênh lệch quang phổ',
			'Bao gồm tất cả các thang màu và chỉ số thường được sử dụng',
			'Lưu trữ 100 tiêu chuẩn và 800 phép đo mẫu',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [],
			},
			{
				title: 'Hiệu suất',
				desc: [],
			},
			{
				title: 'Phần mềm tích hợp',
				desc: [],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [],
			},
		],
		documents: [
			{
				title: 'MiniScan EZ User Manual',
				href: 'https://www.hunterlab.com/media/documents/users_manual_for_miniscan_ez.pdf',
			},
			{
				title: 'MiniScan EZ Brochure',
				href: 'https://www.hunterlab.com/media/documents/miniscan-ez-brochure.pdf',
			},
			{
				title: 'MiniScan EZ Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/miniscan-ez-quick-start-guide.pdf',
			},
			{
				title: 'MiniScan EZ Specifications',
				href: 'https://www.hunterlab.com/media/documents/MiniScan_EZ_Specifications.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/miniscan-ez-data-display.png',
			'https://www.hunterlab.com/media/original_images/miniscan-ez-configurations.png',
			'https://www.hunterlab.com/media/original_images/miniscan-ez-handle-thumb-tip-control.png',
		],
	},
	{
		id: '10',
		name: 'Máy Đo Màu Di Động MiniScan EZ 4000',
		image: '/products/miniscan-ez-spectrophotometer.png',
		category: '2',
		industries: ['1', '3', '6', '7', '8', '9'],
		desc: 'Máy đo màu di động MiniScan EZ 4000 có màn hình lớn, trọng lượng nhẹ và được thiết kế công thái học để thao tác bằng một tay. Với phần mềm tích hợp bao gồm hầu hết các thang màu và chỉ số phản xạ công nghiệp chính. MiniScan EZ 4000 cho phép các nhà sản xuất đánh giá dễ dàng và chính xác chất lượng sản phẩm của mình.',
		features: [
			'Trọng lượng nhẹ với tay cầm bọc cao su tạo sự thoải mái cho người vận hành',
			'Thao tác dễ dàng bằng một tay, điều hướng bằng đầu ngón tay cái của các chức năng',
			'Màn hình LCD lớn, dễ đọc',
			'Hiển thị dữ liệu màu, dữ liệu chênh lệch màu, biểu đồ màu, dữ liệu quang phổ, chênh lệch dữ liệu quang phổ, biểu đồ quang phổ, biểu đồ chênh lệch quang phổ',
			'Bao gồm tất cả các thang màu và chỉ số thường được sử dụng',
			'Lưu trữ 100 tiêu chuẩn và 800 phép đo mẫu',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [],
			},
			{
				title: 'Hiệu suất',
				desc: [],
			},
			{
				title: 'Phần mềm tích hợp',
				desc: [],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [],
			},
		],
		documents: [
			{
				title: 'MiniScan EZ Brochure',
				href: 'https://www.hunterlab.com/media/documents/miniscan-ez-brochure.pdf',
			},
			{
				title: 'MiniScan EZ Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/miniscan-ez-quick-start-guide.pdf',
			},
			{
				title: 'MiniScan EZ Specifications',
				href: 'https://www.hunterlab.com/media/documents/MiniScan_EZ_Specifications.pdf',
			},
			{
				title: 'MiniScan EZ User Manual',
				href: 'https://www.hunterlab.com/media/documents/users_manual_for_miniscan_ez.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/miniscan-ez-data-display.png',
			'https://www.hunterlab.com/media/original_images/miniscan-ez-configurations.png',
			'https://www.hunterlab.com/media/original_images/miniscan-ez-handle-thumb-tip-control.png',
		],
	},
	{
		id: '11',
		name: 'Thiết Bị Phân Tích Màu Sắc Và Kiểm Soát Quy Trình SpectraTrend HT',
		image: '/products/spectratrend-ht-spectrophotometer.png',
		category: '3',
		industries: ['1', '3', '6', '7', '8', '9'],
		desc: 'Máy so màu SpectraTrend HT hỗ trợ triển khai các chương trình quản lý chất lượng toàn diện ngày nay như LQM, PAT, Six Sigma, DMAIC và các chương trình khác có chung mục tiêu là tạo ra chất lượng sản phẩm nhất quán và giảm lãng phí. Việc sử dụng SpectraTrend HT có thể tạo điều kiện thuận lợi để tăng cường GMP trong doanh nghiệp, giảm rủi ro biến đổi chất lượng màu sắc và các chi phí liên quan thông qua việc giám sát màu sắc theo quy trình trong thời gian thực.',
		features: [
			'Hiển thị dữ liệu thời gian thực có thể điều chỉnh',
			'Thiết kế cho môi trường sản xuất khắc nghiệt',
			'Đo đồng thời và chính xác 2 chỉ tiêu chiều cao – màu sắc ',
			'Tích hợp dễ dàng vào hệ thống điều khiển nhà máy hoặc hoạt động độc lập.',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [],
			},
			{
				title: 'Hiệu suất',
				desc: [],
			},
			{
				title: 'Phần mềm tích hợp',
				desc: [],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [],
			},
		],
		documents: [
			{
				title: 'SpectraTrend HT Brochure',
				href: 'https://www.hunterlab.com/media/documents/spectratrend-ht-brochure.pdf',
			},
			{
				title: 'SpectraTrend HT Specifications',
				href: 'https://www.hunterlab.com/media/documents/spectratrend-ht-specifications.pdf',
			},
			{
				title: 'SpectraTrend HT User Manual',
				href: 'https://www.hunterlab.com/media/documents/02_SpectraTrend_HT_Users_Guide_v_3.3_A60-1014-954.pdf',
			},
			{
				title: 'SpectraTrend HT Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/SpectraTrend_Quick_Start_Guide_ver_1.0.pdf',
			},
		],
		assets: [],
	},
	{
		id: '12',
		name: 'Máy Đo Màu Quang Phổ UltraScan VIS',
		image: '/products/ultrascan-vis-spectrophotometer.png',
		category: '1',
		industries: ['1', '2', '3', '5', '8'],
		desc: 'Độ chính xác tuyệt vời trên các mẫu mờ, trong suốt, nửa trong suốt và thậm chí là tối và có độ bão hòa cao Máy đo màu quang phổ UltraScan VIS dễ dàng đo màu dạng phản xạ và dạng truyền qua cũng như sự truyền qua lớp phủ và đáp ứng các tiêu chuẩn CIE, ASTM và USP để đo màu chính xác. Do thỏa thuận đặc biệt giữa các thiết bị và tính ổn định lâu dài, bạn có thể tin tưởng rằng sự khác biệt giữa các phép đo là do sự thay đổi màu sắc của sản phẩm, không phải do sự thay đổi của thiết bị. Vật liệu nằm trên đường giới hạn của tiêu chuẩn chấp nhận, sẽ không bị từ chối một cách không cần thiết.',
		features: [
			'Đo độ phản xạ, độ truyền qua và lớp phủ',
			'Dải bước sóng 360 nm – 780 nm',
			'Độ phân giải quang học và khoảng báo cáo là 10 nm',
			'Hai vùng đo độ phản xạ của màu',
			'Thoả thuận đặt biệt giữa các thiết bị',
			'Hiệu chuẩn và kiểm soát UV tự động',
			'Khoang truyền động lớn mở trên ba mặt',
			'Bao gồm phần mềm EasyMatch QC',
		],
		specifications: [
			{
				title: 'Phương Pháp Đo Lường',
				desc: [
					'Nguyên lý đo lường: Máy quang phổ/máy đo màu hai chùm tia',
					'Hình học: Phản xạ khuếch tán d/8°, truyền dẫn tổng thể d/8°, truyền dẫn thông thường d/0°',
					'Máy quang phổ/Máy đo màu: Hai bộ tán sắc, mỗi bộ có mảng diode 512 phần tử và lưới nhiễu xạ lõm, độ phân giải cao',
					'Đường kính quả cầu: 152 mm (6 in.)',
					'Lớp phủ quả cầu: Spectraflect™ cho quả cầu, Duraflect™ cho tấm cổng và cửa loại bỏ gương',
					'Kích thước cổng/Khu vực đo:',
					'- Đường kính cổng/Đường kính vùng nhìn trong các chế độ phản xạ RSIN/RSEX',
					'+ Chế độ nhìn vùng lớn (LAV): Chiếu sáng 25 mm (1 in)/Đo 19 mm (0.75 in)',
					'+ Chế độ nhìn vùng trung bình (MAV): Chiếu sáng 13 mm (0.5 in)/Đo 9 mm (0.35 in)',
					'+ Chế độ nhìn vùng nhỏ (SAV): Chiếu sáng 7 mm (0.25 in)/Đo 4 mm (0.16 in)',
					'- Đường kính cổng/Đường kính vùng nhìn trong các chế độ truyền dẫn TTRAN',
					'+ Chế độ nhìn vùng lớn (LAV): Chiếu sáng 25 mm (1 in)/Đo 17.4 mm (0.69 in)',
					'+ Chế độ nhìn vùng trung bình (MAV): Chiếu sáng 25 mm (1 in)/Đo 13.2 mm (0.52 in)',
					'+ Chế độ nhìn vùng nhỏ (SAV): Chiếu sáng 25 mm (1 in)/Đo 11.6 mm (0.46 in)',
					'- Đường kính cổng/Đường kính vùng nhìn trong chế độ truyền dẫn RTRAN nơi ống kính là trường nhìn cho tất cả các khu vực',
					'+ Chế độ nhìn vùng lớn (LAV): Chiếu sáng 17 mm (0.67 in)/Đo 17 mm (0.67 in)',
					'+ Chế độ nhìn vùng trung bình (MAV): Chiếu sáng 17 mm (0.67 in)/Đo 17 mm (0.67 in)',
					'+ Chế độ nhìn vùng nhỏ (SAV): Chiếu sáng 17 mm (0.67 in)/Đo 17 mm (0.67 in)',
				],
			},
			{
				title: 'Thông số kỹ thuật',
				desc: [
					'Thành phần phản xạ: Tự động bao gồm (RSIN) hoặc loại trừ (RSEX) trong phản xạ',
					'Dải quang phổ: 360 nm - 780 nm, bao gồm toàn bộ dải nhìn thấy theo CIE',
					'Độ phân giải bước sóng: < 2 nm',
					'Băng thông hiệu dụng: 10 nm, tương đương hình tam giác',
					'Khoảng báo cáo: 10 nm',
					'Dải quang phổ đo: 0-150%',
					'Độ phân giải quang phổ: 0,003 % (báo cáo là 0,01 %)',
					'Nguồn sáng: Đèn Xenon xung (3 bóng), được hiệu chuẩn và kiểm soát trong dải UV',
					'Kiểm soát UV tự động:',
					'- Bộ lọc cắt 400 nm để kiểm soát và loại trừ UV',
					'- Tùy chọn bộ lọc cắt 420 nm để loại trừ UV',
					'Số lần phát sáng mỗi lần đo: 1 lần trong chế độ LAV (4 lần trong chế độ SAV)',
					'Thời gian đo: Dưới 5 giây',
					'Chế độ truyền dẫn: Tổng thể (TTRAN) và Thông thường (RTRAN)',
					'Khoang truyền dẫn:',
					'- Lớn và mở ở 3 mặt',
					'- Kích thước: 10,2 cm sâu x 35,6 cm rộng x 16,5 cm cao (4 in. sâu x 14 in. rộng x 6,5 in. cao)',
					'Tuân thủ tiêu chuẩn:',
					'- Phản xạ: CIE 15:2004, ISO 7724/1, ASTM E1164, DIN 5033, Phần 7 và JIS Z 8722 Điều kiện C',
					'- Truyền dẫn: CIE 15:2004, ASTM E1164, DIN 5033 Phần 7 và JIS Z 8722 Điều kiện E, G Độ mờ tuân thủ theo ASTM D1003 Mục 8, Quy trình B',
				],
			},
			{
				title: 'Hiệu suất',
				desc: [
					'Sự đồng nhất giữa các thiết bị đo màu (IIA):',
					'- ∆E* < 0.15 CIE L*a*b* (Trung bình) trên bộ gạch BCRA II',
					'- < 0.25 CIE L*a*b* (Tối đa) trên bộ gạch BCRA II',
					'Khả năng tái tạo (20 Lần đo):',
					'- < 0,03 ∆E* CIE L*a*b* trên ô màu trắng ở chế độ LAV và SAV',
					'- < 0,05 ∆E* CIE L*a*b* trên ô denim màu xanh ở chế độ LAV và SAV',
					'- Độ lặp lại quang phổ: Phạm vi tối đa 0,20 trong khoảng từ 435 nm đến 695 nm',
				],
			},
			{
				title: 'Vật lý/ Điện tử',
				desc: [
					'Kích thước:',
					'- Chiều cao: 27.9 cm (11 in.)',
					'- Chiều rộng: 42.0 cm (16.5 in.)',
					'- Độ sâu: 49.8 cm (19.6 in.)',
					'- Trọng lượng: 20.4 kg (45 lbs)',
					'Nguồn điện:',
					'- 100 đến 240 VAC, 47 đến 63 Hz',
					'- 60 watts khi ở trạng thái chờ, 120 watts tối đa',
					'Giao diện: Cổng nối tiếp RS-232C, tốc độ 19.200 baud, đầu cắm DB9 (cổng cái)',
					'Môi trường vận hành: Nhiệt độ từ 10° đến 40°C (50° đến 104°F), độ ẩm 10% đến 90%, không ngưng tụ',
					'Môi trường lưu trữ: Nhiệt độ từ -21° đến 66°C (-5° đến 150°F), độ ẩm 10% đến 90%, không ngưng tụ',
					'Phụ kiện tiêu chuẩn:',
					'- Tấm chuẩn trắng được hiệu chuẩn',
					'- Chứng chỉ truy xuất nguồn gốc',
					'- Bẫy ánh sáng hiệu chuẩn màu đen',
					'- Tấm hiệu chuẩn không truyền dẫn',
					'- Tấm chẩn đoán màu xanh lá',
					'- Bộ lọc chẩn đoán bước sóng',
					'- Tiêu chuẩn huỳnh quang',
					'- Kẹp mẫu phản xạ',
					'- Khẩu độ LAV (vùng lớn)',
					'- Khẩu độ MAV (vùng trung bình)',
					'- Khẩu độ SAV (vùng nhỏ)',
					'- Cáp RS-232C',
					'- Bộ chuyển đổi USB sang Serial',
					'- Dây nguồn',
					'- Phần mềm EasyMatch QC',
					'- Sổ tay cơ bản EasyMatch QC',
				],
			},
		],
		documents: [
			{
				title: 'UltraScan VIS Brochure',
				href: 'https://www.hunterlab.com/media/documents/ultrascan-vis-brochure.pdf',
			},
			{
				title: 'UltraScan Specifications',
				href: 'https://www.hunterlab.com/media/documents/ultrascan-vis-specifications.pdf',
			},
			{
				title: 'UltraScan VIS Supplemental Manual for EasyMatch QC',
				href: 'https://www.hunterlab.com/media/documents/Supplemental_Manual_for_EZMQC_UltraScan_VIS.pdf',
			},
		],
		assets: [],
	},
	{
		id: '13',
		name: 'EasyMatch QC: Phần Mềm Kiểm Soát Chất Lượng Màu',
		image: '/products/easymatch-qc-product.png',
		category: '3',
		industries: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
		desc: 'EasyMatch QC rất dễ sử dụng và có thể được cài đặt để chỉ hiển thị thông tin bạn muốn. EasyMatch QC mang đến khả năng gần như vô hạn để trình bày và so sánh thông tin màu sắc của bạn. Dữ liệu màu và dữ liệu quang phổ được hiển thị bằng số ở dạng bảng tính hoặc đồ họa dưới dạng biểu đồ màu, biểu đồ quang phổ và biểu đồ xu hướng. Màn hình EZ View được đơn giản hóa chỉ hiển thị dữ liệu tiêu chuẩn và mẫu cuối cùng được đo và đạt/không đạt (tuỳ chọn). Color Render mô phỏng trực quan màu sắc trên màn hình máy tính của bạn. EasyMatch QC có khả năng lưu giữ hồ sơ điện tử. Phiên bản phần mềm này bảo vệ và duy trì hồ sơ đầy đủ và chính xác, giới hạn quyền truy cập hệ thống, thực hiện kiểm tra quyền hạn và bao gồm chữ ký điện tử. Nó đáp ứng các yêu cầu phần mềm để tuân thủ 21 CFR Part 11. EasyMatch QC có các ngôn ngữ tiếng Trung, tiếng Anh, tiếng Pháp, tiếng Đức, tiếng Bồ Đào Nha, tiếng Ý, tiếng Nhật, tiếng Nga và tiếng Tây Ban Nha và tương thích với tất cả các hệ điều hành hiện tại của Microsoft.',
		features: [
			'Nhiều chế độ xem dữ liệu có thể định tuỳ chỉnh',
			'Đơn giản hóa việc lưu trữ và gọi lại dữ liệu',
			'Cơ sở dữ liệu có thể tìm kiếm đầy đủ',
			'Các trường công thức cho phép tính toán các chỉ số tùy chỉnh',
			'Người quản lý người dùng với các đặc quyền truy cập tùy chỉnh',
			'Khả năng tùy chỉnh báo cáo in',
		],
		specifications: [
			{
				title: 'Features',
				desc: [],
			},
			{
				title: 'Instrument Compatibility',
				desc: [],
			},
			{
				title: 'Minimum Computer Requirements',
				desc: [],
			},
		],
		documents: [
			{
				title: 'EasyMatch QC User Manual',
				href: 'https://www.hunterlab.com/media/documents/EasyMatch_QC_Manual_A60-1012-402_3.6.pdf',
			},
			{
				title: 'EasyMatch QC Lessons',
				href: 'https://www.hunterlab.com/media/documents/easymatch-qc-lessons.pdf',
			},
			{
				title: 'EasyMatch QC Specifications',
				href: 'https://www.hunterlab.com/media/documents/EasyMatch_QC_Specifications-1-23.pdf',
			},
			{
				title: 'EasyMatch QC Quick Start Guide',
				href: 'https://www.hunterlab.com/media/documents/EasyMatchQC_QuickStartGuide_LetterSize-3.pdf',
			},
		],
		assets: [
			'https://www.hunterlab.com/media/original_images/Data_Views.jpg',
			'https://www.hunterlab.com/media/original_images/2D_color_plot.jpg',
		],
	},
]
